import { SiteSettings } from '../constants';
import { PrintableEntry } from '../components/PrintPreview';
import { waitForGlobal } from './dataUtils';

export const exportLogToPDF = async (
    summary: string,
    entries: PrintableEntry[],
    siteSettings: SiteSettings
) => {
    const jspdf = await waitForGlobal<any>('jspdf');
    const { jsPDF } = jspdf;
    const doc = new jsPDF();
    const now = new Date();

    // Header
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(now.toLocaleString(), 14, 15);
    doc.setFontSize(12);
    doc.setTextColor(40);
    doc.text(siteSettings.companyName, doc.internal.pageSize.getWidth() - 14, 15, { align: 'right' });

    // Title
    doc.setFontSize(22);
    doc.setTextColor(0);
    doc.text("Timesheet & Activity Report", 14, 30);
    doc.setFontSize(14);
    doc.setTextColor(100);
    doc.text(`User: ${siteSettings.creator.name}`, 14, 38);

    // Work Summary
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Work Summary", 14, 55);
    doc.setFontSize(11);
    doc.setTextColor(50);
    const splitSummary = doc.splitTextToSize(summary, doc.internal.pageSize.getWidth() - 28);
    doc.text(splitSummary, 14, 62);

    // Table
    const tableColumn = ["Date", "Time", "Type", "Description", "Duration"];
    const tableRows = entries.map(e => [e.date, e.time, e.type, e.description, e.duration]);
    
    (doc as any).autoTable({
        head: [tableColumn],
        body: tableRows,
        startY: 80,
        theme: 'grid',
        headStyles: { fillColor: [34, 197, 94] }, // Emerald 500
        styles: { fontSize: 9 },
        columnStyles: {
            0: { cellWidth: 25 },
            1: { cellWidth: 20 },
            2: { cellWidth: 30 },
            3: { cellWidth: 'auto' },
            4: { cellWidth: 25 },
        }
    });

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(9);
        doc.setTextColor(150);
        doc.text(
            `Page ${i} of ${pageCount}`,
            doc.internal.pageSize.getWidth() / 2,
            doc.internal.pageSize.getHeight() - 10,
            { align: 'center' }
        );
        doc.text(
            `Generated by JSTYP.me Ai tools`,
            14,
            doc.internal.pageSize.getHeight() - 10
        );
    }

    doc.save(`timesheet-report_${now.toISOString().split('T')[0]}.pdf`);
};